import Link from 'next/link';
import {Logo} from './page';
export const problems=[['Lost in the noise','Great content competes for attention in an increasingly crowded digital world.'],['Built for engagement','Traditional discovery systems often reward what captures the most attention—not necessarily what creates the most value.'],['Value gets diluted','Creators often give up control, transparency, and a significant share of the economics behind their work.']];
export const pillars=[['Find Your Audience','Help stories travel beyond traditional distribution barriers and reach audiences who genuinely value them.'],['Build Your Community','Turn passive audiences into active fans through deeper, participatory experiences.'],['Keep More Value','Create more transparent creator economics with direct, real-time payouts and up to 90% creator revenue share.']];
export function Problems(){return <><div className="problem-grid">{problems.map(([title,copy],i)=><article key={title}><span className="problem-symbol" aria-hidden="true">{['≋','⌁','◴'][i]}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="closing">We believe distribution can work <em>differently.</em></p></>}
export function Solution(){return <section className="section solution wrap"><p className="eyebrow">02 / THE LUMOSVERSE APPROACH</p><div className="section-top"><h2>Built around creators,<br/>stories, and audiences.</h2><p className="intro">Lumosverse rethinks content distribution around a more direct relationship between the people who create stories and the people who value them.</p></div><div className="pillars">{pillars.map(([title,copy],i)=><article key={title}><span className="pillar-num">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Link className="text-link underlined" href="/creators">Explore for Creators <span>↗</span></Link></section>}
export function Traction(){return <section className="section traction wrap"><p className="eyebrow">04 / BUILT IN THE REAL WORLD</p><h2>Built from zero.<br/><span>Tested with real creators and audiences.</span></h2><div className="metrics">{[['10K+','Monthly content uploads'],['20K','New users acquired in six months'],['+60%','Creator retention'],['90%','Creator revenue share']].map(([n,label],i)=><div key={n}>{i===3&&<small>UP TO</small>}<strong>{n}</strong><p>{label}</p></div>)}</div><div className="secondary-metrics"><p><strong>3 months</strong><span>From development to go-to-market</span></p><p><strong>6-person cross-functional team</strong><span>Product · Engineering · Marketing</span></p></div></section>}
export function Experiences(){return <section className="section experiences wrap"><div><p className="eyebrow">05 / CREATOR EXPERIENCES</p><h2>From audiences<br/>to <em>superfans.</em></h2><p className="intro">We worked with creators to experiment with new ways for audiences to discover, collect, and participate in the stories they love.</p></div><div className="experience-list"><div><span>01</span><h3>Discover a story.</h3><p>A first encounter becomes a connection.</p></div><div><span>02</span><h3>Become part of it.</h3><p>Exclusive digital drops and superfan experiences.</p></div><div><span>03</span><h3>Go beyond the audience.</h3><p>More ways to collect, participate, and belong.</p></div></div></section>}
export function Mission(){return <section className="section mission wrap"><p className="eyebrow">06 / OUR MISSION</p><h2>The future of storytelling<br/>isn't just about creating more.<br/><em>It's about helping the right stories<br/>find the right audiences.</em></h2><p className="intro">As the barriers to creation continue to fall, discovery becomes more important than ever. Lumosverse is built on a simple belief: meaningful stories deserve a better chance to travel across audiences, communities, and borders.</p><p className="mission-close">Every story deserves its audience.</p><Link href="/about" className="text-link">About Lumosverse <span>↗</span></Link></section>}
export function Contact(){return <section className="contact-section wrap"><div><h2>Have a story worth sharing?</h2><p>Let's help it find its audience.</p></div><a href="mailto:info@lumosverse.io" className="button">Get in Touch <span>↗</span></a></section>}
export function Footer(){return <footer className="footer wrap"><div className="footer-main"><div><Logo/><p>Every story deserves its audience.</p></div><nav aria-label="Footer navigation"><Link href="/">Home</Link><Link href="/creators">For Creators</Link><Link href="/how-it-works">How It Works</Link><Link href="/about">About</Link></nav><nav aria-label="Contact and social"><a href="mailto:info@lumosverse.io">info@lumosverse.io ↗</a><a href="https://www.linkedin.com/in/zhaoliusc/" target="_blank" rel="noopener noreferrer">LinkedIn · Zhaoli ↗</a></nav></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Lumosverse</span><span>STORIES WITHOUT BOUNDARIES.</span></div></footer>}
